#!/usr/bin/env python


"""
A script to run smaller scripts to update all my data to the latest.
"""


import os


def runScript( cmd ):
    print( "*** Running %s ***" % cmd )
    os.system( cmd )


runScript( './src/DataCollectionLib/scripts/update-yahoo-finance-data' )
runScript( './src/DataCollectionLib/scripts/populate-daily-closing-price-csvs' )
runScript( './src/WebDashboardLib/create-html.py' )


print( "\n*** Done! ***" )
