#!/usr/bin/env python

import sys, os
import numpy as np
import multiprocessing as mp
sys.path.insert( 0, '../Utils' )
import MacrotrendsUtil

###########
# Constants
###########
THIS_DIR = os.path.dirname( __file__ )
ROOT_DIR = os.path.realpath( os.path.join( THIS_DIR, '../../..'\
 ) )

tickerListPath = THIS_DIR + '/tickers.txt'
financialsCsvDestDir = ROOT_DIR + '/data/RawData/FinacialsFromMacrotrends'
NUM_PROCESSES = 1


print( "***** UPDATING MACROTRENDS DATA *****" )

# Read the list of tickers from a file
with open( tickerListPath, 'r' ) as f:
   tickers = f.readlines()
tickers = [ t.strip() for t in tickers ]


def fetchData( tickerList ):
   for ticker in tickerList:
      financialsCsvDest = financialsCsvDestDir + '/%s.csv' % ticker
      MacrotrendsUtil.getFinancialsCsv( ticker, financialsCsvDest )

fetchData( tickers )
